version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vyacheslavgizov/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: vyacheslavgizov/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: vyacheslavgizov/foodgram_gateway
    ports:
      - 9090:80
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    depends_on:
      - backend
      - frontend