# Generated by Django 4.2.16 on 2024-11-25 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_options_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridients',
            options={'default_related_name': 'recipe_ingridients', 'verbose_name': 'Ингредиенты для рецепта', 'verbose_name_plural': 'Ингредиенты для рецепта'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes_images/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=2200, verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingridients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', help_text=('Введите цвет тега (например: #ADD8E6)',), max_length=7, validators=[django.core.validators.RegexValidator(message='Требуемый формат: HEX', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Цвет тега в hex-формате'),
        ),
    ]
