# Generated by Django 4.2.16 on 2024-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingridients_options_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Укажите необходимые ингредиенты', through='recipes.RecipeIngridients', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
