# Generated by Django 4.2.16 on 2024-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unsubcribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='unsubcribe_to_yourself', violation_error_message='Нельзя быть подписанным на себя.'),
        ),
    ]
