# Generated by Django 3.2.3 on 2024-12-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlpathKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlpath', models.CharField(max_length=32, unique=True, verbose_name='Исходная ссылка')),
                ('key', models.CharField(max_length=15, unique=True, verbose_name='Исходная ссылка')),
            ],
            options={
                'verbose_name': 'Пара: путь-ключ',
                'verbose_name_plural': 'Пары: путь-ключ',
            },
        ),
    ]
