# Generated by Django 3.2.3 on 2024-12-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlpathKey',
            new_name='LinkKey',
        ),
        migrations.AlterModelOptions(
            name='linkkey',
            options={'verbose_name': 'Пара: ссылка-ключ', 'verbose_name_plural': 'Пары: ссылка-ключ'},
        ),
        migrations.RenameField(
            model_name='linkkey',
            old_name='urlpath',
            new_name='link',
        ),
    ]
