# Generated by Django 3.2.3 on 2024-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_users_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_users_shoppingcart',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_users_favorite_records'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_users_shoppingcart_records'),
        ),
    ]
