# Generated by Django 3.2.3 on 2024-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20241204_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Метка'),
        ),
    ]
