# Generated by Django 3.2.3 on 2024-12-10 15:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unsubcribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='unsubscribe_to_yourself'),
        ),
    ]
