# Generated by Django 3.2.3 on 2024-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241216_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32, unique=True, verbose_name='Исходная ссылка')),
                ('key', models.CharField(max_length=15, unique=True, verbose_name='Исходная ссылка')),
            ],
            options={
                'verbose_name': 'Пара: ссылка-ключ',
                'verbose_name_plural': 'Пары: ссылка-ключ',
            },
        ),
    ]
