# Generated by Django 3.2.3 on 2024-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241222_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source_link',
            field=models.CharField(max_length=124, unique=True, verbose_name='Исходная ссылка'),
        ),
    ]
