# Generated by Django 3.2.3 on 2024-12-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_linkkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkkey',
            name='key',
            field=models.CharField(max_length=15, unique=True, verbose_name='Ключ'),
        ),
    ]
