# Generated by Django 3.2.3 on 2024-12-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_linkkey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=32, unique=True, verbose_name='Путь')),
                ('key', models.CharField(max_length=15, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Пара: путь-ключ',
                'verbose_name_plural': 'Пары: путь-ключ',
            },
        ),
        migrations.DeleteModel(
            name='LinkKey',
        ),
    ]
